/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kmart.glb -T -j 
Files: kmart.glb [76.29MB] > C:\Users\Uzair\Documents\New folder (2)\kmart-transformed.glb [11.71MB] (85%)
*/
'use client'
import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { Select } from '@react-three/postprocessing'
import { useRouter } from 'next/navigation'

export default function Kmart (props) {
  const { nodes, materials } = useGLTF('/kmart-transformed.glb')
  const [hovered, setHovered] = useState({})
  const router = useRouter();

  // Function to handle hover status
  const handleHover = (event, meshName, status) => {
    event.stopPropagation()
    setHovered(prev => ({
      ...prev,
      [meshName]: status
    }))
  }
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.WatermelonHalf_MAT_FruitCrates_0.geometry}
        material={materials.MAT_FruitCrates}
        position={[29.349, 6.581, -26.918]}
        rotation={[-Math.PI / 2, 0, -0.633]}
        scale={[0.069, 0.06, 0.06]}
      />
      <mesh
        geometry={nodes.Object_6001.geometry}
        material={materials.material_0}
        position={[-7.674, 7.082, -7.082]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <mesh
        geometry={nodes.Object_6003.geometry}
        material={materials.material_0}
        position={[-51.777, 7.082, -89.91]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <mesh
        geometry={nodes.Object_10001.geometry}
        material={materials.material_0}
        position={[-13.078, 7.037, 2.444]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <mesh
        geometry={nodes.Object_10003.geometry}
        material={materials.material_0}
        position={[-57.181, 7.037, -80.384]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <mesh
        geometry={nodes.Object_16001.geometry}
        material={materials.material_0}
        position={[-10.639, 2.407, 6.61]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <mesh
        geometry={nodes.Object_16003.geometry}
        material={materials.material_0}
        position={[-54.742, 2.407, -76.219]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <mesh
        geometry={nodes.Object_20001.geometry}
        material={materials.material_0}
        position={[-7.451, 4.55, -2.563]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <mesh
        geometry={nodes.Object_20003.geometry}
        material={materials.material_0}
        position={[-51.554, 4.55, -85.392]}
        rotation={[0, -1.571, 0]}
        scale={8.393}
      />
      <group
        position={[-106.189, 11.879, -93.295]}
        rotation={[0, -0.274, 0]}
        scale={[0.53, 0.716, 0.53]}
      >
        <mesh
          geometry={nodes.pPlane37_lambert2_0.geometry}
          material={materials.lambert2}
        />
        <mesh
          geometry={nodes.pPlane37_lambert2_0_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          geometry={nodes.pPlane37_lambert2_0_2.geometry}
          material={materials.lambert3}
        />
        <mesh
          geometry={nodes.pPlane37_lambert2_0_3.geometry}
          material={materials.lambert6}
        />
        <RigidBody
          colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
          lockTranslations // Lock translations to prevent movement during physics simulation
          lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
        >
          <mesh
            geometry={nodes.pPlane37_lambert2_0_4.geometry}
            material={materials.lambert9}
          />
        </RigidBody>
        <mesh
          geometry={nodes.pPlane37_lambert2_0_5.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.pPlane37_lambert2_0_6.geometry}
          material={materials.stnder}
        />
        <RigidBody
          colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
          lockTranslations // Lock translations to prevent movement during physics simulation
          lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
        >
          <mesh
            geometry={nodes.pPlane37_lambert2_0_7.geometry}
            material={materials.plane}
          />
        </RigidBody>
        <mesh
          geometry={nodes.pPlane37_lambert2_0_8.geometry}
          material={materials.lichter}
        />
      </group>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials['Material.012']}
        position={[-97.011, 1.151, -91.576]}
        rotation={[0.002, 0.599, 0.001]}
        scale={0.268}
      />
      <group
        position={[-107.494, 1.927, -86.354]}
        rotation={[0, 0.585, 0]}
        scale={0.004}
      >
        <mesh
          geometry={nodes.Mesh_0007.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0007_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-96.986, 2.73, -97.454]}
        rotation={[-Math.PI, 1.512, -Math.PI]}
        scale={0.006}
      >
        <mesh
          geometry={nodes.Mesh_0007.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0007_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-100.276, 1.616, -85.53]}
        rotation={[0, -0.274, 0]}
        scale={1.302}
      >
        <mesh
          geometry={nodes.Mesh_2.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_2_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group position={[-111.664, 1.296, -84.52]} rotation={[0, 0.625, 0]}>
        <mesh
          geometry={nodes.Mesh_2.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_2_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group position={[-67.515, 1.139, -47.029]} scale={0.207}>
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0.geometry}
          material={materials.geschenk4}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_1.geometry}
          material={materials.kekse}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_2.geometry}
          material={materials.bonbon}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_3.geometry}
          material={materials.coin}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_4.geometry}
          material={materials.haribo}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_5.geometry}
          material={materials.choco}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_6.geometry}
          material={materials.lolli}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_7.geometry}
          material={materials.schale}
        />
        <RigidBody
          colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
          lockTranslations // Lock translations to prevent movement during physics simulation
          lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
        >
          <mesh
            geometry={nodes.pCylinder26_geschenk4_0_8.geometry}
            material={materials.plane2}
          />
        </RigidBody>
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_9.geometry}
          material={materials.kasten1}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_10.geometry}
          material={materials.rolle}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_11.geometry}
          material={materials.pack2}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_12.geometry}
          material={materials.pack1}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_13.geometry}
          material={materials.schleifen}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_14.geometry}
          material={materials.geschenk2}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_15.geometry}
          material={materials.band1}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_16.geometry}
          material={materials.geschenk3}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_17.geometry}
          material={materials.geschenk5}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_18.geometry}
          material={materials.geschenk6}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_19.geometry}
          material={materials.pack3}
        />
        <mesh
          geometry={nodes.pCylinder26_geschenk4_0_20.geometry}
          material={materials.geschenk1}
        />
      </group>
      <group
        position={[-80.996, 18.778, -101.998]}
        rotation={[-1.677, 0.708, 2.819]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-115.16, 21.16, -71.871]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-115.16, 18.384, -71.871]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-115.16, 24.17, -71.871]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-80.996, 15.889, -101.998]}
        rotation={[-1.677, 0.708, 2.819]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-80.996, 18.778, -41.858]}
        rotation={[-1.464, -0.708, -0.323]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-80.996, 15.889, -41.858]}
        rotation={[-1.464, -0.708, -0.323]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-6.791, 19.786, -101.947]}
        rotation={[-1.677, 0.708, 2.819]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights001_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-6.791, 16.897, -101.947]}
        rotation={[-1.677, 0.708, 2.819]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights001_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights001_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-105.728, 6.212, -53.03]}
        rotation={[-Math.PI / 2, 0, 1.082]}
        scale={4.751}
      >
        <mesh
          geometry={nodes.Cube001_WH_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_1.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_2.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_3.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_5.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_6.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_7.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_8.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0_9.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <group
        position={[-46.419, 21.296, -5.299]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights009_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[32.122, 21.296, -5.299]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights009_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[32.122, 21.296, -75.344]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights009_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights009_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-46.414, 18.533, -5.274]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights010_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[32.127, 18.533, -5.274]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights010_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[32.127, 18.533, -75.319]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights010_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights010_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-46.421, 24.275, -5.313]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights011_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[32.12, 24.275, -5.313]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights011_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[32.12, 24.275, -75.358]}
        rotation={[-2.281, -0.081, -1.963]}
        scale={0.126}
      >
        <mesh
          geometry={nodes.Xmas_Lights011_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_4.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Xmas_Lights011_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.Santa.geometry}
        material={materials.Mat_Santa}
        position={[-74.496, 11.966, -45.384]}
        rotation={[0, -1.021, -Math.PI]}
        scale={-5.13}
      />
      <group
        position={[-47.085, 19.06, -64.942]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={4.505}
      >
        <mesh
          geometry={nodes.Text_1.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Text_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text_7.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text_8.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text_9.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.Reindeer.geometry}
        material={materials['material_0.002']}
        position={[-71.409, 9.795, -92.918]}
        rotation={[0, 0.752, 0]}
        scale={8.04}
      />
      <group
        position={[-77.777, 1.264, -97.732]}
        rotation={[-Math.PI / 2, 0, 1.082]}
        scale={4.751}
      >
        <mesh
          geometry={nodes.Cube001_WH_0001.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube001_WH_0001_1.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <mesh
        geometry={nodes.Gift_Carpet.geometry}
        material={materials.boden}
        position={[-67.389, 0.263, -45.812]}
        scale={0.207}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial002}
        position={[-8.284, 14.236, 31.813]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_4001.geometry}
        material={materials.PaletteMaterial002}
        position={[-26.934, 14.236, 31.813]}
        scale={[0.08, 0.097, 0.097]}
      />
      <mesh
        geometry={nodes.Object_5001.geometry}
        material={materials.PaletteMaterial005}
        position={[-13.153, 11.856, 31.043]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_5002.geometry}
        material={materials.PaletteMaterial005}
        position={[-30.665, 11.856, 31.043]}
        scale={[0.076, 0.097, 0.097]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial005}
        position={[-3.465, 11.856, 31.613]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_8001.geometry}
        material={materials.PaletteMaterial005}
        position={[-23.029, 11.856, 31.613]}
        scale={[0.076, 0.097, 0.097]}
      />
      <mesh
        geometry={nodes.Object_8002.geometry}
        material={materials.PaletteMaterial005}
        position={[17.275, 11.856, 31.613]}
        scale={[0.091, 0.097, 0.097]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.PaletteMaterial002}
        position={[1.331, 9.01, 31.623]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_4002.geometry}
        material={materials.PaletteMaterial002}
        position={[12.675, 14.236, 31.813]}
        rotation={[Math.PI, 0, 0]}
        scale={-0.097}
      />
      <mesh
        geometry={nodes.Object_9001.geometry}
        material={materials.PaletteMaterial002}
        position={[2.976, 9.01, 31.623]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_5003.geometry}
        material={materials.PaletteMaterial005}
        position={[8.154, 11.856, 31.043]}
        scale={[0.091, 0.097, 0.097]}
      />
      <group
        position={[-33.347, 18.754, -43.4]}
        scale={[50.92, 13.444, 31.053]}
      >
        {/* <RigidBody
          colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
          lockTranslations // Lock translations to prevent movement during physics simulation
          lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
        > */}
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        {/* </RigidBody> */}

        <RigidBody
          colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
          lockTranslations // Lock translations to prevent movement during physics simulation
          lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
        >
          <mesh
            geometry={nodes.Cube_2.geometry}
            material={materials['Material.001']}
          />
        </RigidBody>

        {/* <RigidBody
          colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
          lockTranslations // Lock translations to prevent movement during physics simulation
          lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
        > */}
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials['Green Wall']}
        />
        {/* </RigidBody> */}

        <mesh geometry={nodes.Cube_4.geometry} material={materials.Roof} />
      </group>

      <RigidBody
        colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
        lockTranslations // Lock translations to prevent movement during physics simulation
        lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
      >
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.plaster}
          position={[-6.639, 12.648, 30.892]}
          scale={[50.92, 13.444, 31.053]}
        />
      </RigidBody>
      <group
        position={[-117.309, 13.649, -71.657]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[5.971, 3.28, 0.307]}
      >
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube011_1.geometry}
          material={materials['Green Wall']}
        />
      </group>
      <group
        position={[0.88, 28.822, 32.616]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={24.025}
      >
        <mesh
          geometry={nodes.Text003.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text003_1.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <group
        position={[0.88, 22.439, -101.708]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={13.866}
      >
        <mesh
          geometry={nodes.Text003.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Text003_1.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.plaster}
        position={[-89.733, 19.014, 19.55]}
        scale={18.29}
      />
      <RigidBody
        colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
        lockTranslations // Lock translations to prevent movement during physics simulation
        lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
      >
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials['Material.011']}
          position={[-6.263, 0.254, 66.657]}
          scale={[72.22, 13.444, 31.053]}
        />
      </RigidBody>

      <RigidBody
        colliders='trimesh' // Type of collider shape for the wall (a cuboid in this case)
        lockTranslations // Lock translations to prevent movement during physics simulation
        lockRotations // Lock rotations to prevent unwanted rotations during physics simulation
      >
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials['Material.011']}
          position={[-6.263, 0.254, 137.662]}
          scale={[72.22, 13.444, 31.053]}
        />
      </RigidBody>
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.plaster}
        position={[75.004, 19.014, 19.55]}
        rotation={[-Math.PI, 0, 0]}
        scale={-18.29}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.plaster}
        position={[0.099, 19.014, 167.916]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-18.29}
      />
      <group position={[-0.814, 4.418, -19.311]} scale={0.012}>
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group position={[-17.943, 4.418, -19.311]} scale={0.012}>
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group position={[17.897, 4.418, -19.311]} scale={0.012}>
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[-70.095, 11.924, -42.245]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.018}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[-46.666, 4.418, -67.925]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.012}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[-46.469, 4.418, -50.795]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.012}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[-46.469, 4.418, -86.636]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.012}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[31.328, 22.455, -40.754]}
        rotation={[0, -1.571, 0]}
        scale={0.023}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[29.376, 23.211, -99.502]}
        rotation={[0, -0.664, 0]}
        scale={0.023}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group position={[-45.966, 22.879, -101.033]} scale={0.018}>
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group position={[-80.209, 20.894, -100.743]} scale={0.018}>
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[-93.877, 11.924, -42.245]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.018}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[-114.697, 23.044, -100.765]}
        rotation={[0, 1.237, 0]}
        scale={0.018}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <group
        position={[-112.82, 23.044, -42.757]}
        rotation={[-Math.PI, 0.802, -Math.PI]}
        scale={0.018}
      >
        <mesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_0_1.geometry}
          material={materials['object_2.001']}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.PaletteMaterial002}
        position={[-4.65, 2.616, -20.153]}
        scale={[0.239, 2.444, 0.239]}
      />

      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.lambert9}
        position={[-22.554, 3.299, -20.145]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.221]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.lambert9}
        position={[-13.247, 3.299, -20.145]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.221]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.lambert9}
        position={[13.271, 3.299, -20.145]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.221]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.lambert9}
        position={[-47.303, 3.299, -46.185]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.221]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials.lambert9}
        position={[-47.303, 3.299, -55.491]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.221]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials.lambert9}
        position={[-47.303, 3.299, -82.009]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.221]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.PaletteMaterial002}
        position={[-47.312, 2.616, -68.368]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.239, 2.444, 0.239]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.lambert9}
        position={[-47.303, 3.201, -90.213]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.221]}
      />
      <group position={[-7.705, 20.946, -51.793]} scale={[12.06, 1.903, 0.307]}>
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube003_2.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Cube003_3.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials.PaletteMaterial002}
        position={[-7.716, 28.514, -51.783]}
        scale={[0.156, 1.588, 0.156]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials.PaletteMaterial002}
        position={[-47.109, 25.924, -63.255]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.156, 1.588, 0.156]}
      />
      <group position={[-10.382, 20.605, 0]} scale={[8.07, 1.109, 8.07]}>
        <mesh
          geometry={nodes.Cylinder_1.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={nodes.Cylinder_2.material}
        />
        <mesh
          geometry={nodes.Cylinder_3.geometry}
          material={materials.PaletteMaterial004}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.PaletteMaterial002}
        position={[-10.382, 27.78, 0]}
        scale={[0.284, 6.636, 0.284]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.PaletteMaterial002}
        position={[-56.533, 27.78, -87.024]}
        rotation={[-Math.PI, 1.566, -Math.PI]}
        scale={[0.284, 6.636, 0.284]}
      />
      <group
        position={[-56.533, 20.605, -87.024]}
        rotation={[-Math.PI, 1.566, -Math.PI]}
        scale={[8.07, 1.109, 8.07]}
      >
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.PaletteMaterial004}
        />
      </group>
      <group
        position={[-45.734, 7.472, -6.998]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[5.971, 3.28, 0.307]}
      >
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials['Green Wall']}
        />
      </group>
      <mesh
        geometry={
          nodes.Supermarket_Chips_Shelf_Supermarket_Chips_Shelf_0.geometry
        }
        material={materials.Supermarket_Chips_Shelf}
        position={[29.839, 5.62, -15.774]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={8.096}
      />
      <group
        position={[-44.851, 5.76, 12.582]}
        rotation={[0, 1.571, 0]}
        scale={[0.306, 6.763, 13.526]}
      >
        <mesh
          geometry={nodes.Cube130.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube130_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-44.851, 5.76, -25.971]}
        rotation={[0, 1.571, 0]}
        scale={[0.306, 6.763, 13.526]}
      >
        <mesh
          geometry={nodes.Cube130.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube130_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group position={[-45.152, 7.459, 9.817]} scale={[0.178, 1.2, 0.769]}>
        <mesh
          geometry={nodes.Cube182.geometry}
          material={materials['Material.056']}
        />
        <mesh
          geometry={nodes.Cube182_1.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube182_2.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube182_3.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube182_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube182_5.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube182_6.geometry}
          material={materials['Material.063']}
        />
        <mesh
          geometry={nodes.Cube182_7.geometry}
          material={materials['Material.061']}
        />
      </group>
      <group position={[-45.152, 7.459, -28.737]} scale={[0.178, 1.2, 0.769]}>
        <mesh
          geometry={nodes.Cube182.geometry}
          material={materials['Material.056']}
        />
        <mesh
          geometry={nodes.Cube182_1.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube182_2.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube182_3.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube182_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube182_5.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube182_6.geometry}
          material={materials['Material.063']}
        />
        <mesh
          geometry={nodes.Cube182_7.geometry}
          material={materials['Material.061']}
        />
      </group>
      <group
        position={[-6.992, 7.417, -46.588]}
        rotation={[0, 1.571, 0]}
        scale={[0.322, 7.111, 14.223]}
      >
        <mesh
          geometry={nodes.Cube068.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_2.geometry}
          material={materials['Material.056']}
        />
        <mesh
          geometry={nodes.Cube068_3.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_4.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_5.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_7.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube068_8.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube068_9.geometry}
          material={materials['Material.063']}
        />
      </group>
      <group
        position={[10.819, 7.417, -49.781]}
        rotation={[Math.PI, -1.571, 0]}
        scale={[-0.322, -7.111, -14.223]}
      >
        <mesh
          geometry={nodes.Cube068.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_2.geometry}
          material={materials['Material.056']}
        />
        <mesh
          geometry={nodes.Cube068_3.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_4.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_5.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_7.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube068_8.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube068_9.geometry}
          material={materials['Material.063']}
        />
      </group>
      <group
        position={[29.678, 7.417, -46.588]}
        rotation={[0, 1.571, 0]}
        scale={[0.322, 7.111, 14.223]}
      >
        <mesh
          geometry={nodes.Cube068.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_2.geometry}
          material={materials['Material.056']}
        />
        <mesh
          geometry={nodes.Cube068_3.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_4.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_5.geometry}
          material={materials['Material.057']}
        />
        <mesh
          geometry={nodes.Cube068_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube068_7.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube068_8.geometry}
          material={materials['Material.061']}
        />
        <mesh
          geometry={nodes.Cube068_9.geometry}
          material={materials['Material.063']}
        />
      </group>
      {/* <Select enabled={hovered['Snacks']}> */}

      <mesh
        geometry={nodes.Cricket_Ball.geometry}
        material={materials['Cricket Ball']}
        position={[9.976, 5.105, -101.264]}
        scale={5.065}
      />
      {/* </Select> */}
      <group position={[10.259, 7.595, -101.226]} scale={5.065}>
        <Select enabled={hovered['BasketBall']}>
          <mesh
            geometry={nodes.V1Basket.geometry}
            material={materials.BasketV1Mat}
            onClick={e => {
              e.stopPropagation()
              router.push(
                `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
              )
            }}
            onPointerOver={e => handleHover(e, 'BasketBall', true)}
            onPointerOut={e => handleHover(e, 'BasketBall', false)}
          />
        </Select>
        <Select enabled={hovered['Bowling']}>
          <mesh
            geometry={nodes.V1Basket_1.geometry}
            material={materials['Bowling.001']}
            onClick={e => {
              e.stopPropagation()
              router.push(
                `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
              )
            }}
            onPointerOver={e => handleHover(e, 'Bowling', true)}
            onPointerOut={e => handleHover(e, 'Bowling', false)}
          />
        </Select>
      </group>

      <Select enabled={hovered['Bat']}>
        <mesh
          geometry={nodes.Bat.geometry}
          material={materials['shoes/bat/pads']}
          position={[-2.89, 3.388, -88.105]}
          scale={5.065}
          onClick={e => {
            e.stopPropagation()
            router.push(
              `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
            )
          }}
          onPointerOver={e => handleHover(e, 'Bat', true)}
          onPointerOut={e => handleHover(e, 'Bat', false)}
        />
      </Select>

      <Select enabled={hovered['Cap']}>
        <mesh
          geometry={nodes.Cap.geometry}
          material={materials['ball/glove/cap .001']}
          position={[13.013, 9.125, -101.209]}
          scale={5.065}
          onClick={e => {
            e.stopPropagation()
            router.push(
              `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
            )
          }}
          onPointerOver={e => handleHover(e, 'Cap', true)}
          onPointerOut={e => handleHover(e, 'Cap', false)}
        />
      </Select>

      <Select enabled={hovered['Football_1']}>
        <mesh
          geometry={nodes.Football_1.geometry}
          material={materials['shoes/bat/pads']}
          position={[8.674, 6.045, -101.224]}
          scale={5.065}
          onClick={e => {
            e.stopPropagation()
            router.push(
              `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
            )
          }}
          onPointerOver={e => handleHover(e, 'Football_1', true)}
          onPointerOut={e => handleHover(e, 'Football_1', false)}
        />
      </Select>
      <mesh
        geometry={nodes.Hand_Bags.geometry}
        material={materials['bag/shoes/shirt']}
        position={[-11.621, 7.943, -97.187]}
        scale={5.065}
      />
      <group position={[-11.843, 5.357, -97.236]} scale={5.065}>
        <mesh
          geometry={nodes.Object_1003.geometry}
          material={materials.RACKFRONT}
        />
        <mesh
          geometry={nodes.Object_1003_1.geometry}
          material={materials.RACK}
        />
        <mesh
          geometry={nodes.Object_1003_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Object_1003_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Object_1003_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Object_1003_5.geometry}
          material={materials.counter}
        />
      </group>

      <mesh
        geometry={nodes.Sportgloves.geometry}
        material={materials['ball/glove/cap .001']}
        position={[4.134, 3.981, -88.397]}
        scale={5.065}
      />
      <mesh
        geometry={nodes.TennisRacket.geometry}
        material={materials.TennisRacketV1Mat}
        position={[-7.378, 4.283, -88.345]}
        scale={5.065}
      />
      <mesh
        geometry={nodes.Glass_Protector.geometry}
        material={materials['Glass Material']}
        position={[-4.804, 4.47, -81.425]}
        scale={5.065}
      />
      <mesh
        geometry={nodes.Fuel_Can.geometry}
        material={materials['Material.010']}
        position={[4.017, 4.221, -74.449]}
        scale={5.065}
      />
      <Select enabled={hovered['CricketHelmet']}>
        <mesh
          geometry={nodes.Cricket_helmet.geometry}
          material={materials['ball/glove/cap .001']}
          position={[7.116, 9.186, -101.217]}
          scale={5.065}
          onClick={e => {
            e.stopPropagation()
            router.push(
              `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
            )
          }}
          onPointerOver={e => handleHover(e, 'CricketHelmet', true)}
          onPointerOut={e => handleHover(e, 'CricketHelmet', false)}
        />
      </Select>
      <mesh
        geometry={nodes.Football_2.geometry}
        material={materials['Bowling.001']}
        position={[10.005, 5.385, -101.334]}
        scale={5.065}
      />
      <Select enabled={hovered['BikeGlove']}>
        <mesh
          geometry={nodes.Bike_Gloves.geometry}
          material={materials['helmet/gloves']}
          position={[-23.185, 7.554, -101.386]}
          scale={5.065}
          onClick={e => {
            e.stopPropagation()
            router.push(
              `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
            )
          }}
          onPointerOver={e => handleHover(e, 'BikeGlove', true)}
          onPointerOut={e => handleHover(e, 'BikeGlove', false)}
        />
      </Select>
      <Select enabled={hovered['Helmet']}>
        <mesh
          geometry={nodes.Helmets.geometry}
          material={materials['helmet/gloves']}
          position={[-33.031, 10.428, -101.377]}
          scale={5.065}
          onClick={e => {
            e.stopPropagation()
            router.push(
              `https://www.kmart.com/tvs-electronics/b-1231469079?adcell=hp_CatLink_CE`
            )
          }}
          onPointerOver={e => handleHover(e, 'Helmet', true)}
          onPointerOut={e => handleHover(e, 'Helmet', false)}
        />
      </Select>
      <mesh
        geometry={nodes.Fuel_Can_2.geometry}
        material={materials['Material.010']}
        position={[1.333, 4.105, -74.698]}
        scale={5.065}
      />
      <mesh
        geometry={nodes.Tool_Box.geometry}
        material={materials['Material.010']}
        position={[-2.532, 4.143, -74.167]}
        scale={5.065}
      />
      <mesh
        geometry={nodes.Helmet_yellow.geometry}
        material={materials['Material.010']}
        position={[-7.167, 3.722, -74.454]}
        scale={5.065}
      />
      <mesh
        geometry={nodes.Leather_Boots.geometry}
        material={materials['Material.010']}
        position={[-13.988, 3.847, -74.443]}
        scale={5.065}
      />
      <group position={[9.939, 12.271, -100.866]} scale={5.065}>
        <mesh
          geometry={nodes.Body_Mat_Body_0.geometry}
          material={materials.PaletteMaterial006}
        />
        <mesh
          geometry={nodes.Body_Mat_Body_0_1.geometry}
          material={materials['tyre rack']}
        />
        <mesh
          geometry={nodes.Body_Mat_Body_0_2.geometry}
          material={materials.Tyre}
        />
        <mesh
          geometry={nodes.Body_Mat_Body_0_3.geometry}
          material={materials.PaletteMaterial006}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/kmart-transformed.glb')
